import { Geist, Geist_Mono, Roboto_Condensed } from "next/font/google";
import "./globals.css";

import NavBar from "@/components/Header";
import Footer from "@/components/Footer";
import { Providers } from "./RTK/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const robotoCondensed = Roboto_Condensed({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body

        className={`${geistSans.variable} ${geistMono.variable} ${robotoCondensed.variable} antialiased`}
      >
        <Providers>
          <NavBar /> {children}<Footer /></Providers>
      </body>
    </html>
  );
}
